# Generated by Django 5.1.7 on 2025-11-10 03:22

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCuS10FeS10MoS10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_cut_cus', models.FloatField(verbose_name='Control CuT-CuS')),
                ('cut', models.FloatField(verbose_name='CuT')),
                ('cus10', models.FloatField(verbose_name='CuS10')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisCuS4FeS4MoS4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control1_cut_cus', models.FloatField(verbose_name='Control1 CuT-CuS')),
                ('l_ppm_cus_fe', models.FloatField(verbose_name='L. ppm CusFe')),
                ('l_ppm_bk_fes4', models.FloatField(verbose_name='L. ppm-BK FeS4')),
                ('fes4', models.FloatField(verbose_name='FeS4 (%)')),
                ('control2_cut_fes4', models.FloatField(verbose_name='Control2 CuT-FeS4')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisCuSCuSFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_ppm_cus_fe', models.FloatField(verbose_name='L. ppm CuSFe')),
                ('l_ppm_bk_cus_fe', models.FloatField(verbose_name='L. ppm-Bk CuSFe')),
                ('cus_fe', models.FloatField(verbose_name='CuSFe (%)')),
                ('control2_cut_cus_fe', models.FloatField(verbose_name='Control2 CuT-CuSFe')),
                ('cut', models.FloatField(verbose_name='CuT')),
                ('cus_c', models.FloatField(verbose_name='CuSC')),
                ('cus_fe_2', models.FloatField(verbose_name='CuSFe')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisCuTestConsH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control1_cut_cutest', models.FloatField(verbose_name='Control1 CuT-CuTest')),
                ('cut', models.FloatField(verbose_name='CuT')),
                ('cut_test', models.FloatField(verbose_name='CuTest')),
                ('gaston_ml', models.FloatField(verbose_name='Gaston mL')),
                ('gasto_bk_ml', models.FloatField(verbose_name='Gasto Bk mL')),
                ('n_naco3', models.FloatField(verbose_name='N NaCO3')),
                ('alicuota', models.FloatField(verbose_name='Alicuota')),
                ('consumo_h', models.FloatField(verbose_name='Consumo H+')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisCuTFeZn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_ppm_fe', models.FloatField(verbose_name='L. ppm Fe')),
                ('l_ppm_bk_fe', models.FloatField(verbose_name='L. ppm-BK Fe')),
                ('fe', models.FloatField(verbose_name='Fe (%)')),
                ('l_ppm_zn', models.FloatField(verbose_name='L. ppm Zn')),
                ('l_ppm_bk_zn', models.FloatField(verbose_name='L. ppm-BK Zn')),
                ('zn', models.FloatField(verbose_name='Zn (%)')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_ppm_ag', models.FloatField(verbose_name='L. ppm Ag')),
                ('l_ppm_ag_bk', models.FloatField(verbose_name='L. ppm Ag-bk')),
                ('ag', models.FloatField(verbose_name='Ag (ppm)')),
                ('l_ppm_as', models.FloatField(verbose_name='L. ppm As')),
                ('l_ppm_as_bk', models.FloatField(verbose_name='L. ppm As-bk')),
                ('analisis_as', models.FloatField(verbose_name='As (%)')),
                ('l_ppm_mo', models.FloatField(verbose_name='L. ppm Mo')),
                ('l_ppm_mo_bk', models.FloatField(verbose_name='L. ppm Mo-bk')),
                ('mo', models.FloatField(verbose_name='Mo (%)')),
                ('l_ppm_pb', models.FloatField(verbose_name='L. ppm Pb')),
                ('l_ppm_pb_bk', models.FloatField(verbose_name='L. ppm Pb-Bk')),
                ('pb', models.FloatField(verbose_name='Pb (%)')),
                ('l_ppm_cu', models.FloatField(verbose_name='L. ppm Cu')),
                ('l_ppm_cu_bk', models.FloatField(verbose_name='L. ppm Cu-bk')),
                ('cu', models.FloatField(verbose_name='Cu (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, unique=True)),
                ('rut', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('gramos', models.FloatField()),
                ('miligramos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MuestraMasificada',
            fields=[
                ('Prefijo', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipoMuestra', models.CharField(default='M', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('contenido_completo', models.TextField()),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_model', models.CharField(choices=[('Orden_de_trabajo', 'Orden de trabajo'), ('Hoja_de_trabajo', 'Hoja de trabajo')], max_length=200)),
                ('accion', models.CharField(choices=[('Crear', 'Crear'), ('Modificar', 'Modificar'), ('Eliminar', 'Eliminar'), ('Balanza', 'Balanza'), ('Absorcion', 'Absorción')], max_length=200)),
                ('modelt_id', models.CharField(max_length=200, verbose_name='ID registro')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Novedades',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('rut', models.CharField(max_length=200, unique=True)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('rolname', models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('quimico_A', 'Químico A'), ('quimico_B', 'Químico B'), ('quimicoC', 'Químico C')], max_length=200)),
                ('turno', models.CharField(choices=[('Dia', 'Dia'), ('Noche', 'Noche')], max_length=200)),
                ('datejoined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('firstname', models.CharField(max_length=150, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=150, verbose_name='Apellido')),
                ('numero', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clientes', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='HojaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(default='M', max_length=200)),
                ('Duplicado', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Estandar', models.ManyToManyField(related_name='Estandar', to='api.estandar')),
            ],
        ),
        migrations.CreateModel(
            name='HojaTrabajoQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_HDT', models.CharField(max_length=200, verbose_name='Nro Hoja de trabajo')),
                ('confirmar_balanza', models.BooleanField(default=False, verbose_name='Confirmar_Balanza')),
                ('confirmar_Absorcion', models.BooleanField(default=False, verbose_name='Confirmar_Absorción')),
                ('HojaTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojas_trabajo_target', to='api.hojatrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='LotesAbsorción',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_LT', models.CharField(default=0, max_length=200, verbose_name='Nro de Lote')),
                ('curv_1', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Curvatura 1')),
                ('curv_2', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Curvatura 2')),
                ('curv_3', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Curvatura 3')),
                ('curv_4', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Curvatura 4')),
                ('hoja_trabajo', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resultado_hoja', to='api.hojatrabajoquimico')),
            ],
            options={
                'verbose_name': 'Lote de Absorción',
                'verbose_name_plural': 'Lotes de Absorción',
            },
        ),
        migrations.CreateModel(
            name='MetodoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('metodologia', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='api.cliente')),
                ('elementos', models.ManyToManyField(related_name='elementos', to='api.elementos')),
            ],
        ),
        migrations.AddField(
            model_name='hojatrabajo',
            name='MetodoAnalisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Metodo_de_Analisis', to='api.metodoanalisis'),
        ),
        migrations.AddField(
            model_name='hojatrabajo',
            name='MuestraMasificada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MuestraMasificada', to='api.muestramasificada'),
        ),
        migrations.CreateModel(
            name='ODT',
            fields=[
                ('Fec_Recep', models.DateField()),
                ('Fec_Finalizacion', models.DateField()),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Número de OT')),
                ('Prefijo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Muestra inicial')),
                ('Responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable envío')),
                ('Prioridad', models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=200, verbose_name='Prioridad')),
                ('TipoMuestra', models.CharField(blank=True, choices=[('Sondaje', 'Sondaje'), ('Subterranea', 'Subterranea'), ('Tronadura', 'Tronadura')], max_length=200, verbose_name='Tipo de Muestra')),
                ('Referencia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Batch')),
                ('Comentarios', models.CharField(blank=True, max_length=255)),
                ('Cant_Muestra', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de Muestras')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='muestramasificada',
            name='odt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masificaciones', to='api.odt'),
        ),
        migrations.AddField(
            model_name='hojatrabajo',
            name='odt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojas_trabajo', to='api.odt'),
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unidad', models.CharField(max_length=200)),
                ('VA', models.FloatField()),
                ('DS', models.FloatField()),
                ('Min', models.FloatField()),
                ('Max', models.FloatField()),
                ('Elementos', models.ManyToManyField(related_name='Elementos', to='api.elementos')),
            ],
        ),
        migrations.AddField(
            model_name='estandar',
            name='parametros',
            field=models.ManyToManyField(related_name='Parametro', to='api.parametros'),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_emision', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='api.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='odt',
            name='Proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto'),
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField()),
                ('elemento', models.CharField(max_length=100)),
                ('nbo', models.CharField(max_length=100)),
                ('ident', models.CharField(max_length=100)),
                ('indexCurv', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='posisión de curvatura')),
                ('t', models.CharField(max_length=100)),
                ('peso_m', models.FloatField(verbose_name='PesoM. (g)')),
                ('v_ml', models.FloatField(verbose_name='V. mL')),
                ('l_ppm', models.FloatField(verbose_name='L. ppm')),
                ('l_ppm_bk', models.FloatField(verbose_name='L. ppm-BK')),
                ('porcentaje', models.FloatField(verbose_name='Porcentaje (%)')),
                ('hoja_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoja_de_trabajo', to='api.hojatrabajo')),
                ('muestraMasificada', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='muestra_masificada', to='api.muestramasificada')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dilucion', models.FloatField(default=0, verbose_name='dilución de elemento')),
                ('resultadoAnalisis', models.FloatField(verbose_name='Resultado de Análisis')),
                ('leyAnalisis', models.FloatField(default=0, verbose_name='Ley de Análisis')),
                ('fecha_emision', models.DateField(default=0, verbose_name='Fecha de Emisión')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_elemento', to='api.elementos')),
                ('lote_absorcion', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_lote', to='api.lotesabsorción')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_muestra', to='api.muestra')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
    ]
