# Generated by Django 5.0.4 on 2024-09-16 04:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Analisis_metodo', models.CharField(max_length=200, verbose_name='Método de Análisis')),
                ('descripcion', models.CharField(max_length=255)),
                ('Formula', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('tipo', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True, verbose_name='Activo')),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True)),
                ('numero_atomico', models.IntegerField(blank=True, null=True)),
                ('masa_atomica', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ODT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nro_OT', models.CharField(max_length=200, unique=True)),
                ('Fec_Recep', models.DateField()),
                ('Cliente', models.CharField(max_length=200)),
                ('Proyecto', models.CharField(max_length=200)),
                ('Despacho', models.CharField(max_length=200)),
                ('Envio', models.CharField(max_length=200, verbose_name='Envío')),
                ('Muestra', models.CharField(max_length=200, verbose_name='Código de muestras')),
                ('Referencia', models.CharField(max_length=200)),
                ('Comentarios', models.CharField(blank=True, max_length=255)),
                ('InicioCodigo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Inicio Código')),
                ('FinCodigo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fin Código')),
                ('Cant_Muestra', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de Muestras')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(blank=True, max_length=200, null=True)),
                ('rolname', models.CharField(choices=[('Cliente', 'Cliente'), ('Supervisor', 'Supervisor'), ('Administrador', 'Administrador'), ('QuimicoA', 'Químico A'), ('QuimicoB', 'Químico B'), ('QuimicoC', 'Químico C')], default='Cliente', max_length=200)),
                ('is_superuser', models.BooleanField(default=False)),
                ('credential', models.CharField(blank=True, max_length=50, verbose_name='Credential')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('user', models.OneToOneField(limit_choices_to={'rolname': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_muestra', models.CharField(max_length=50, unique=True, verbose_name='ID Muestra')),
                ('peso_muestra', models.FloatField(verbose_name='Peso Muestra')),
                ('volumen', models.FloatField(verbose_name='Volumen')),
                ('dilucion', models.FloatField(verbose_name='Dilución')),
                ('Elemento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ots', to='api.elementos')),
                ('analisis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ots', to='api.analisis')),
                ('odt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ots', to='api.odt')),
            ],
        ),
        migrations.CreateModel(
            name='LecturasElementos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lectura', models.IntegerField(verbose_name='Lectura')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_elementos', to='api.analisis')),
                ('elementos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_elementos', to='api.elementos')),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_elementos', to='api.ot')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='api.cliente')),
            ],
        ),
    ]
