# Generated by Django 5.0.4 on 2024-09-16 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odt',
            name='Cliente',
            field=models.ForeignKey(limit_choices_to={'rolname': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='odt',
            name='Despacho',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Despacho'),
        ),
        migrations.AlterField(
            model_name='odt',
            name='Envio',
            field=models.ForeignKey(limit_choices_to={'rolname__in': ['QuimicoA', 'QuimicoB', 'QuimicoC']}, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to=settings.AUTH_USER_MODEL),
        ),
    ]
