# Generated by Django 5.0.4 on 2024-11-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='curvaturaelementos',
            constraint=models.UniqueConstraint(fields=('cliente', 'elemento'), name='unique_cliente_elemento'),
        ),
    ]
