# Generated by Django 5.0.4 on 2024-07-17 04:53

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Analisis_metodo', models.CharField(max_length=200, verbose_name='Método de Análisis')),
                ('descripcion', models.CharField(max_length=255)),
                ('Formula', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LecturasElementos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lectura', models.IntegerField(verbose_name='Lectura')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_elementos', to='api.analisis')),
                ('elementos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_elementos', to='api.elementos')),
            ],
        ),
        migrations.CreateModel(
            name='ODT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nro_OT', models.CharField(max_length=200)),
                ('Fec_Recep', models.DateField()),
                ('Cant_Muestra', models.IntegerField(verbose_name='Cantidad Muestra')),
                ('Cliente', models.CharField(max_length=200)),
                ('Proyecto', models.CharField(max_length=200)),
                ('Despacho', models.CharField(max_length=200)),
                ('Envio', models.CharField(max_length=200)),
                ('Muestra', models.CharField(max_length=200)),
                ('Referencia', models.CharField(max_length=200)),
                ('Comentarios', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_muestra', models.CharField(max_length=50, verbose_name='ID Muestra')),
                ('peso_muestra', models.FloatField(verbose_name='Peso Muestra')),
                ('volumen', models.FloatField(verbose_name='Volumen')),
                ('dilucion', models.FloatField(verbose_name='Dilución')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ots', to='api.analisis')),
                ('odt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ots', to='api.odt')),
            ],
        ),
        migrations.RemoveField(
            model_name='analisiscus10fes10mos10',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='analisiscus4fes4mos4',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='analisiscuscusfe',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='analisiscutestconsh',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='analisiscutfezn',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='analisismulti',
            name='muestra',
        ),
        migrations.DeleteModel(
            name='Elemento',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='muestra',
        ),
        migrations.DeleteModel(
            name='Parametro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_administrador',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_cliente',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_new_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_quimico',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_supervisor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='credential',
            field=models.CharField(blank=True, max_length=50, verbose_name='Credential'),
        ),
        migrations.AddField(
            model_name='user',
            name='rolname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='lecturaselementos',
            name='ot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_elementos', to='api.ot'),
        ),
        migrations.DeleteModel(
            name='AnalisisCuS10FeS10MoS10',
        ),
        migrations.DeleteModel(
            name='AnalisisCuS4FeS4MoS4',
        ),
        migrations.DeleteModel(
            name='AnalisisCuSCuSFe',
        ),
        migrations.DeleteModel(
            name='AnalisisCuTestConsH',
        ),
        migrations.DeleteModel(
            name='AnalisisCuTFeZn',
        ),
        migrations.DeleteModel(
            name='AnalisisMulti',
        ),
        migrations.DeleteModel(
            name='Muestra',
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
