# Generated by Django 5.0.4 on 2024-09-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odt',
            name='Cant_Muestra',
        ),
        migrations.AddField(
            model_name='odt',
            name='FinCodigo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fin Código'),
        ),
        migrations.AddField(
            model_name='odt',
            name='InicioCodigo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Inicio Código'),
        ),
        migrations.AlterField(
            model_name='odt',
            name='Muestra',
            field=models.CharField(max_length=200, verbose_name='Código de muestras'),
        ),
    ]
