# Generated by Django 5.0.4 on 2024-11-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_novedades_alter_hojatrabajoquimico_hojatrabajo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurvaturaElementos',
        ),
    ]
