# Generated by Django 5.0.4 on 2024-09-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_odt_cant_muestra_odt_fincodigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='odt',
            name='Nro_OT',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
