# Generated by Django 5.0.4 on 2024-11-10 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_curvaturaelementos_unique_cliente_elemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='muestraMasificada',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='muestra_masificada', to='api.muestramasificada'),
        ),
    ]
