# Generated by Django 5.0.4 on 2024-07-18 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analisis_elementos_lecturaselementos_odt_ot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='analisis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ots', to='api.analisis'),
        ),
    ]
