# Generated by Django 5.0.4 on 2024-09-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analisis_updated_at_cliente_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odt',
            name='Turno',
            field=models.CharField(choices=[('DIA', 'Día'), ('NOCHE', 'Noche')], default='DIA', max_length=10, verbose_name='Turno'),
        ),
    ]
