# Generated by Django 5.0.4 on 2024-09-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_odt_updated_at_alter_odt_nro_ot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='id_muestra',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID Muestra'),
        ),
    ]
