# Generated by Django 5.0.4 on 2024-08-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ot_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementos',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='elementos',
            name='masa_atomica',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementos',
            name='numero_atomico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementos',
            name='simbolo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
