# Generated by Django 5.0.4 on 2024-12-01 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_curvaturaelementos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotesabsorción',
            options={'verbose_name': 'Lote de Absorción', 'verbose_name_plural': 'Lotes de Absorción'},
        ),
        migrations.RemoveField(
            model_name='lotesabsorción',
            name='ID_HDT',
        ),
        migrations.AddField(
            model_name='lotesabsorción',
            name='ID_LT',
            field=models.CharField(default=0, max_length=200, verbose_name='Nro de Lote'),
        ),
        migrations.AddField(
            model_name='lotesabsorción',
            name='curv_1',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Curvatura 1'),
        ),
        migrations.AddField(
            model_name='lotesabsorción',
            name='curv_2',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Curvatura 2'),
        ),
        migrations.AddField(
            model_name='lotesabsorción',
            name='curv_3',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Curvatura 3'),
        ),
        migrations.AddField(
            model_name='lotesabsorción',
            name='curv_4',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Curvatura 4'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='leyAnalisis',
            field=models.FloatField(default=0, verbose_name='ley de Análisis'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='fecha_emision',
            field=models.DateField(default=0, verbose_name='Fecha de Emisión'),
        ),
    ]
