# Generated by Django 5.0.4 on 2024-11-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_muestra_muestramasificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojatrabajo',
            name='confirmar_balanza',
            field=models.BooleanField(default=False, verbose_name='Confirmar Balanza'),
        ),
    ]
