# Generated by Django 5.0.4 on 2024-09-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_odt_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odt',
            name='Nro_OT',
            field=models.CharField(max_length=200, unique=True, verbose_name='Código de ODT'),
        ),
    ]
