# Generated by Django 5.0.4 on 2024-09-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ot_id_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odt',
            name='Muestra',
            field=models.CharField(max_length=200, unique=True, verbose_name='Código de muestras'),
        ),
    ]
