# Generated by Django 5.0.4 on 2024-12-02 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lotesabsorción_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultado',
            options={'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
        migrations.RemoveField(
            model_name='lotesabsorción',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='hoja_trabajo',
        ),
        migrations.AddField(
            model_name='lotesabsorción',
            name='hoja_trabajo',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resultado_hoja', to='api.hojatrabajo'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='lote_absorcion',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_lote', to='api.lotesabsorción'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_elemento', to='api.elementos'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='leyAnalisis',
            field=models.FloatField(default=0, verbose_name='Ley de Análisis'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_muestra', to='api.muestra'),
        ),
    ]
