# Generated by Django 5.0.4 on 2024-09-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_odt_muestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='odt',
            name='Cant_Muestra',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de Muestras'),
        ),
    ]
