# Generated by Django 5.0.4 on 2024-12-02 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_resultado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotesabsorción',
            name='hoja_trabajo',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resultado_hoja', to='api.hojatrabajoquimico'),
        ),
    ]
