# Generated by Django 5.0.4 on 2024-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_lotesabsorción_hoja_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='dilucion',
            field=models.FloatField(default=0, verbose_name='dilución de elemento'),
        ),
    ]
