# Generated by Django 5.0.4 on 2024-09-20 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_odt_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odt',
            name='Referencia',
        ),
        migrations.AddField(
            model_name='analisis',
            name='Elementos',
            field=models.ManyToManyField(blank=True, to='api.elementos', verbose_name='Elementos'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='Nro_Analisis',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Código de análisis'),
        ),
        migrations.AddField(
            model_name='odt',
            name='Analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.analisis', verbose_name='Análisis'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='disolucion',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Uso de disolución'),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='Analisis_metodo',
            field=models.CharField(max_length=200, verbose_name='Método de análisis'),
        ),
        migrations.AlterField(
            model_name='odt',
            name='Despacho',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Despacho'),
        ),
    ]
