# Generated by Django 5.0.10 on 2025-01-11 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojatrabajo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
