# Generated by Django 5.0.4 on 2024-09-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_odt_referencia_analisis_elementos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ot',
            name='Elemento',
        ),
        migrations.RemoveField(
            model_name='ot',
            name='analisis',
        ),
        migrations.DeleteModel(
            name='LecturasElementos',
        ),
    ]
