# Generated by Django 5.0.4 on 2024-09-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_ot_elemento_remove_ot_analisis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='disolucion',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='volVal',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='uso de volumen'),
        ),
    ]
