# Generated by Django 5.0.4 on 2024-09-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_proyecto_disolucion_proyecto_volval'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
