# Generated by Django 5.0.4 on 2024-10-02 02:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_analisis_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='volVal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credential',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='Desconocido', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_emision',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='is_administrador',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_new_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_quimico',
            field=models.BooleanField(default=False, verbose_name='Químico'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolname',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Supervisor', 'Supervisor'), ('Administrador', 'Administrador'), ('QuimicoA', 'Químico A'), ('QuimicoB', 'Químico B'), ('QuimicoC', 'Químico C')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo'),
        ),
    ]
