# Generated by Django 5.0.4 on 2024-10-06 04:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_cliente_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odt',
            name='Muestra',
        ),
        migrations.AddField(
            model_name='odt',
            name='Prefijo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[api.models.validate_length], verbose_name='Muestra inicial'),
        ),
        migrations.AddField(
            model_name='odt',
            name='Prioridad',
            field=models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=200, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='odt',
            name='Referencia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='odt',
            name='TipoMuestra',
            field=models.CharField(blank=True, choices=[('Sondaje', 'Sondaje'), ('Subterranea', 'Subterranea'), ('Tronadura', 'Tronadura')], max_length=200, verbose_name='Tipo de Muestra'),
        ),
    ]
