# Generated by Django 5.0.4 on 2024-10-07 04:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_odt_muestra_odt_prefijo_odt_prioridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='volVal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odt',
            name='Prefijo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[api.models.validate_length], verbose_name='Codigo de muestras'),
        ),
    ]
