# Generated by Django 5.0.4 on 2024-10-07 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_proyecto_volval_alter_odt_prefijo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaTrabajo',
            fields=[
                ('id_ht', models.AutoField(primary_key=True, serialize=False)),
                ('nro_ht', models.CharField(max_length=100)),
                ('fec_ht', models.DateField(auto_now=True)),
                ('analisis', models.TextField()),
                ('ot_cliente', models.CharField(max_length=100)),
                ('envio', models.BooleanField(default=False)),
                ('en_uso_por', models.CharField(blank=True, max_length=255, null=True)),
                ('cant_muestras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojas_trabajo', to='api.odt')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojas_trabajo_cliente', to='api.cliente')),
                ('odt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojas_odt', to='api.odt')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hojas_proyecto', to='api.proyecto')),
            ],
        ),
    ]
